/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as MyRouteImport } from './routes/my'
import { Route as OperationsRouteRouteImport } from './routes/operations/route'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as PublicAboutRouteImport } from './routes/_public/about'
import { Route as PublicContactRouteImport } from './routes/_public/contact'
import { Route as PublicDonateRouteImport } from './routes/_public/donate'
import { Route as PublicPrivacyRouteImport } from './routes/_public/privacy'
import { Route as PublicTermsRouteImport } from './routes/_public/terms'
import { Route as MyIndexRouteImport } from './routes/my/index'
import { Route as OperationsIndexRouteImport } from './routes/operations/index'
import { Route as OperationsAdminRouteImport } from './routes/operations/admin'
import { Route as OperationsApplicationsRouteImport } from './routes/operations/applications'
import { Route as OperationsComplianceRouteImport } from './routes/operations/compliance'
import { Route as OperationsDocumentsRouteImport } from './routes/operations/documents'
import { Route as OperationsFinanceRouteImport } from './routes/operations/finance'
import { Route as OperationsInsightsRouteImport } from './routes/operations/insights'
import { Route as OperationsMarketingRouteImport } from './routes/operations/marketing'
import { Route as OperationsPeopleRouteImport } from './routes/operations/people'
import { Route as OperationsRiskRouteImport } from './routes/operations/risk'
import { Route as OperationsVendorsRouteImport } from './routes/operations/vendors'
import { Route as OperationsProgramsIndexRouteImport } from './routes/operations/programs/index'
import { Route as OperationsProgramsProgramIdRouteRouteImport } from './routes/operations/programs/$programId/route'
import { Route as OperationsProgramsEventsRouteImport } from './routes/operations/programs/events'
import { Route as OperationsProgramsProgramIdIndexRouteImport } from './routes/operations/programs/$programId/index'
import { Route as OperationsProgramsProgramIdInstancesInstanceIdRouteImport } from './routes/operations/programs/$programId/instances/$instanceId'

const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const MyRoute = MyRouteImport.update({
  id: '/my',
  path: '/my',
  getParentRoute: () => rootRouteImport,
} as any)
const OperationsRouteRoute = OperationsRouteRouteImport.update({
  id: '/operations',
  path: '/operations',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicAboutRoute = PublicAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => PublicRoute,
} as any)
const PublicContactRoute = PublicContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => PublicRoute,
} as any)
const PublicDonateRoute = PublicDonateRouteImport.update({
  id: '/donate',
  path: '/donate',
  getParentRoute: () => PublicRoute,
} as any)
const PublicPrivacyRoute = PublicPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => PublicRoute,
} as any)
const PublicTermsRoute = PublicTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => PublicRoute,
} as any)
const MyIndexRoute = MyIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MyRoute,
} as any)
const OperationsIndexRoute = OperationsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OperationsRouteRoute,
} as any)
const OperationsAdminRoute = OperationsAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => OperationsRouteRoute,
} as any)
const OperationsApplicationsRoute = OperationsApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => OperationsRouteRoute,
} as any)
const OperationsComplianceRoute = OperationsComplianceRouteImport.update({
  id: '/compliance',
  path: '/compliance',
  getParentRoute: () => OperationsRouteRoute,
} as any)
const OperationsDocumentsRoute = OperationsDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => OperationsRouteRoute,
} as any)
const OperationsFinanceRoute = OperationsFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => OperationsRouteRoute,
} as any)
const OperationsInsightsRoute = OperationsInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => OperationsRouteRoute,
} as any)
const OperationsMarketingRoute = OperationsMarketingRouteImport.update({
  id: '/marketing',
  path: '/marketing',
  getParentRoute: () => OperationsRouteRoute,
} as any)
const OperationsPeopleRoute = OperationsPeopleRouteImport.update({
  id: '/people',
  path: '/people',
  getParentRoute: () => OperationsRouteRoute,
} as any)
const OperationsRiskRoute = OperationsRiskRouteImport.update({
  id: '/risk',
  path: '/risk',
  getParentRoute: () => OperationsRouteRoute,
} as any)
const OperationsVendorsRoute = OperationsVendorsRouteImport.update({
  id: '/vendors',
  path: '/vendors',
  getParentRoute: () => OperationsRouteRoute,
} as any)
const OperationsProgramsIndexRoute = OperationsProgramsIndexRouteImport.update({
  id: '/programs/',
  path: '/programs/',
  getParentRoute: () => OperationsRouteRoute,
} as any)
const OperationsProgramsProgramIdRouteRoute =
  OperationsProgramsProgramIdRouteRouteImport.update({
    id: '/programs/$programId',
    path: '/programs/$programId',
    getParentRoute: () => OperationsRouteRoute,
  } as any)
const OperationsProgramsEventsRoute =
  OperationsProgramsEventsRouteImport.update({
    id: '/programs/events',
    path: '/programs/events',
    getParentRoute: () => OperationsRouteRoute,
  } as any)
const OperationsProgramsProgramIdIndexRoute =
  OperationsProgramsProgramIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => OperationsProgramsProgramIdRouteRoute,
  } as any)
const OperationsProgramsProgramIdInstancesInstanceIdRoute =
  OperationsProgramsProgramIdInstancesInstanceIdRouteImport.update({
    id: '/instances/$instanceId',
    path: '/instances/$instanceId',
    getParentRoute: () => OperationsProgramsProgramIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/operations': typeof OperationsRouteRouteWithChildren
  '/': typeof PublicIndexRoute
  '/my': typeof MyRouteWithChildren
  '/about': typeof PublicAboutRoute
  '/contact': typeof PublicContactRoute
  '/donate': typeof PublicDonateRoute
  '/privacy': typeof PublicPrivacyRoute
  '/terms': typeof PublicTermsRoute
  '/operations/admin': typeof OperationsAdminRoute
  '/operations/applications': typeof OperationsApplicationsRoute
  '/operations/compliance': typeof OperationsComplianceRoute
  '/operations/documents': typeof OperationsDocumentsRoute
  '/operations/finance': typeof OperationsFinanceRoute
  '/operations/insights': typeof OperationsInsightsRoute
  '/operations/marketing': typeof OperationsMarketingRoute
  '/operations/people': typeof OperationsPeopleRoute
  '/operations/risk': typeof OperationsRiskRoute
  '/operations/vendors': typeof OperationsVendorsRoute
  '/my/': typeof MyIndexRoute
  '/operations/': typeof OperationsIndexRoute
  '/operations/programs/$programId': typeof OperationsProgramsProgramIdRouteRouteWithChildren
  '/operations/programs/events': typeof OperationsProgramsEventsRoute
  '/operations/programs/': typeof OperationsProgramsIndexRoute
  '/operations/programs/$programId/': typeof OperationsProgramsProgramIdIndexRoute
  '/operations/programs/$programId/instances/$instanceId': typeof OperationsProgramsProgramIdInstancesInstanceIdRoute
}
export interface FileRoutesByTo {
  '/about': typeof PublicAboutRoute
  '/contact': typeof PublicContactRoute
  '/donate': typeof PublicDonateRoute
  '/privacy': typeof PublicPrivacyRoute
  '/terms': typeof PublicTermsRoute
  '/operations/admin': typeof OperationsAdminRoute
  '/operations/applications': typeof OperationsApplicationsRoute
  '/operations/compliance': typeof OperationsComplianceRoute
  '/operations/documents': typeof OperationsDocumentsRoute
  '/operations/finance': typeof OperationsFinanceRoute
  '/operations/insights': typeof OperationsInsightsRoute
  '/operations/marketing': typeof OperationsMarketingRoute
  '/operations/people': typeof OperationsPeopleRoute
  '/operations/risk': typeof OperationsRiskRoute
  '/operations/vendors': typeof OperationsVendorsRoute
  '/': typeof PublicIndexRoute
  '/my': typeof MyIndexRoute
  '/operations': typeof OperationsIndexRoute
  '/operations/programs/events': typeof OperationsProgramsEventsRoute
  '/operations/programs': typeof OperationsProgramsIndexRoute
  '/operations/programs/$programId': typeof OperationsProgramsProgramIdIndexRoute
  '/operations/programs/$programId/instances/$instanceId': typeof OperationsProgramsProgramIdInstancesInstanceIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/operations': typeof OperationsRouteRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/my': typeof MyRouteWithChildren
  '/_public/about': typeof PublicAboutRoute
  '/_public/contact': typeof PublicContactRoute
  '/_public/donate': typeof PublicDonateRoute
  '/_public/privacy': typeof PublicPrivacyRoute
  '/_public/terms': typeof PublicTermsRoute
  '/operations/admin': typeof OperationsAdminRoute
  '/operations/applications': typeof OperationsApplicationsRoute
  '/operations/compliance': typeof OperationsComplianceRoute
  '/operations/documents': typeof OperationsDocumentsRoute
  '/operations/finance': typeof OperationsFinanceRoute
  '/operations/insights': typeof OperationsInsightsRoute
  '/operations/marketing': typeof OperationsMarketingRoute
  '/operations/people': typeof OperationsPeopleRoute
  '/operations/risk': typeof OperationsRiskRoute
  '/operations/vendors': typeof OperationsVendorsRoute
  '/_public/': typeof PublicIndexRoute
  '/my/': typeof MyIndexRoute
  '/operations/': typeof OperationsIndexRoute
  '/operations/programs/$programId': typeof OperationsProgramsProgramIdRouteRouteWithChildren
  '/operations/programs/events': typeof OperationsProgramsEventsRoute
  '/operations/programs/': typeof OperationsProgramsIndexRoute
  '/operations/programs/$programId/': typeof OperationsProgramsProgramIdIndexRoute
  '/operations/programs/$programId/instances/$instanceId': typeof OperationsProgramsProgramIdInstancesInstanceIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/operations'
    | '/'
    | '/my'
    | '/about'
    | '/contact'
    | '/donate'
    | '/privacy'
    | '/terms'
    | '/operations/admin'
    | '/operations/applications'
    | '/operations/compliance'
    | '/operations/documents'
    | '/operations/finance'
    | '/operations/insights'
    | '/operations/marketing'
    | '/operations/people'
    | '/operations/risk'
    | '/operations/vendors'
    | '/my/'
    | '/operations/'
    | '/operations/programs/$programId'
    | '/operations/programs/events'
    | '/operations/programs/'
    | '/operations/programs/$programId/'
    | '/operations/programs/$programId/instances/$instanceId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/about'
    | '/contact'
    | '/donate'
    | '/privacy'
    | '/terms'
    | '/operations/admin'
    | '/operations/applications'
    | '/operations/compliance'
    | '/operations/documents'
    | '/operations/finance'
    | '/operations/insights'
    | '/operations/marketing'
    | '/operations/people'
    | '/operations/risk'
    | '/operations/vendors'
    | '/'
    | '/my'
    | '/operations'
    | '/operations/programs/events'
    | '/operations/programs'
    | '/operations/programs/$programId'
    | '/operations/programs/$programId/instances/$instanceId'
  id:
    | '__root__'
    | '/operations'
    | '/_public'
    | '/my'
    | '/_public/about'
    | '/_public/contact'
    | '/_public/donate'
    | '/_public/privacy'
    | '/_public/terms'
    | '/operations/admin'
    | '/operations/applications'
    | '/operations/compliance'
    | '/operations/documents'
    | '/operations/finance'
    | '/operations/insights'
    | '/operations/marketing'
    | '/operations/people'
    | '/operations/risk'
    | '/operations/vendors'
    | '/_public/'
    | '/my/'
    | '/operations/'
    | '/operations/programs/$programId'
    | '/operations/programs/events'
    | '/operations/programs/'
    | '/operations/programs/$programId/'
    | '/operations/programs/$programId/instances/$instanceId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  OperationsRouteRoute: typeof OperationsRouteRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
  MyRoute: typeof MyRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my': {
      id: '/my'
      path: '/my'
      fullPath: '/my'
      preLoaderRoute: typeof MyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operations': {
      id: '/operations'
      path: '/operations'
      fullPath: '/operations'
      preLoaderRoute: typeof OperationsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/about': {
      id: '/_public/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof PublicAboutRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/contact': {
      id: '/_public/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof PublicContactRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/donate': {
      id: '/_public/donate'
      path: '/donate'
      fullPath: '/donate'
      preLoaderRoute: typeof PublicDonateRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/privacy': {
      id: '/_public/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PublicPrivacyRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/terms': {
      id: '/_public/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof PublicTermsRouteImport
      parentRoute: typeof PublicRoute
    }
    '/my/': {
      id: '/my/'
      path: '/'
      fullPath: '/my/'
      preLoaderRoute: typeof MyIndexRouteImport
      parentRoute: typeof MyRoute
    }
    '/operations/': {
      id: '/operations/'
      path: '/'
      fullPath: '/operations/'
      preLoaderRoute: typeof OperationsIndexRouteImport
      parentRoute: typeof OperationsRouteRoute
    }
    '/operations/admin': {
      id: '/operations/admin'
      path: '/admin'
      fullPath: '/operations/admin'
      preLoaderRoute: typeof OperationsAdminRouteImport
      parentRoute: typeof OperationsRouteRoute
    }
    '/operations/applications': {
      id: '/operations/applications'
      path: '/applications'
      fullPath: '/operations/applications'
      preLoaderRoute: typeof OperationsApplicationsRouteImport
      parentRoute: typeof OperationsRouteRoute
    }
    '/operations/compliance': {
      id: '/operations/compliance'
      path: '/compliance'
      fullPath: '/operations/compliance'
      preLoaderRoute: typeof OperationsComplianceRouteImport
      parentRoute: typeof OperationsRouteRoute
    }
    '/operations/documents': {
      id: '/operations/documents'
      path: '/documents'
      fullPath: '/operations/documents'
      preLoaderRoute: typeof OperationsDocumentsRouteImport
      parentRoute: typeof OperationsRouteRoute
    }
    '/operations/finance': {
      id: '/operations/finance'
      path: '/finance'
      fullPath: '/operations/finance'
      preLoaderRoute: typeof OperationsFinanceRouteImport
      parentRoute: typeof OperationsRouteRoute
    }
    '/operations/insights': {
      id: '/operations/insights'
      path: '/insights'
      fullPath: '/operations/insights'
      preLoaderRoute: typeof OperationsInsightsRouteImport
      parentRoute: typeof OperationsRouteRoute
    }
    '/operations/marketing': {
      id: '/operations/marketing'
      path: '/marketing'
      fullPath: '/operations/marketing'
      preLoaderRoute: typeof OperationsMarketingRouteImport
      parentRoute: typeof OperationsRouteRoute
    }
    '/operations/people': {
      id: '/operations/people'
      path: '/people'
      fullPath: '/operations/people'
      preLoaderRoute: typeof OperationsPeopleRouteImport
      parentRoute: typeof OperationsRouteRoute
    }
    '/operations/risk': {
      id: '/operations/risk'
      path: '/risk'
      fullPath: '/operations/risk'
      preLoaderRoute: typeof OperationsRiskRouteImport
      parentRoute: typeof OperationsRouteRoute
    }
    '/operations/vendors': {
      id: '/operations/vendors'
      path: '/vendors'
      fullPath: '/operations/vendors'
      preLoaderRoute: typeof OperationsVendorsRouteImport
      parentRoute: typeof OperationsRouteRoute
    }
    '/operations/programs/': {
      id: '/operations/programs/'
      path: '/programs'
      fullPath: '/operations/programs/'
      preLoaderRoute: typeof OperationsProgramsIndexRouteImport
      parentRoute: typeof OperationsRouteRoute
    }
    '/operations/programs/$programId': {
      id: '/operations/programs/$programId'
      path: '/programs/$programId'
      fullPath: '/operations/programs/$programId'
      preLoaderRoute: typeof OperationsProgramsProgramIdRouteRouteImport
      parentRoute: typeof OperationsRouteRoute
    }
    '/operations/programs/events': {
      id: '/operations/programs/events'
      path: '/programs/events'
      fullPath: '/operations/programs/events'
      preLoaderRoute: typeof OperationsProgramsEventsRouteImport
      parentRoute: typeof OperationsRouteRoute
    }
    '/operations/programs/$programId/': {
      id: '/operations/programs/$programId/'
      path: '/'
      fullPath: '/operations/programs/$programId/'
      preLoaderRoute: typeof OperationsProgramsProgramIdIndexRouteImport
      parentRoute: typeof OperationsProgramsProgramIdRouteRoute
    }
    '/operations/programs/$programId/instances/$instanceId': {
      id: '/operations/programs/$programId/instances/$instanceId'
      path: '/instances/$instanceId'
      fullPath: '/operations/programs/$programId/instances/$instanceId'
      preLoaderRoute: typeof OperationsProgramsProgramIdInstancesInstanceIdRouteImport
      parentRoute: typeof OperationsProgramsProgramIdRouteRoute
    }
  }
}

interface OperationsProgramsProgramIdRouteRouteChildren {
  OperationsProgramsProgramIdIndexRoute: typeof OperationsProgramsProgramIdIndexRoute
  OperationsProgramsProgramIdInstancesInstanceIdRoute: typeof OperationsProgramsProgramIdInstancesInstanceIdRoute
}

const OperationsProgramsProgramIdRouteRouteChildren: OperationsProgramsProgramIdRouteRouteChildren =
  {
    OperationsProgramsProgramIdIndexRoute:
      OperationsProgramsProgramIdIndexRoute,
    OperationsProgramsProgramIdInstancesInstanceIdRoute:
      OperationsProgramsProgramIdInstancesInstanceIdRoute,
  }

const OperationsProgramsProgramIdRouteRouteWithChildren =
  OperationsProgramsProgramIdRouteRoute._addFileChildren(
    OperationsProgramsProgramIdRouteRouteChildren,
  )

interface OperationsRouteRouteChildren {
  OperationsAdminRoute: typeof OperationsAdminRoute
  OperationsApplicationsRoute: typeof OperationsApplicationsRoute
  OperationsComplianceRoute: typeof OperationsComplianceRoute
  OperationsDocumentsRoute: typeof OperationsDocumentsRoute
  OperationsFinanceRoute: typeof OperationsFinanceRoute
  OperationsInsightsRoute: typeof OperationsInsightsRoute
  OperationsMarketingRoute: typeof OperationsMarketingRoute
  OperationsPeopleRoute: typeof OperationsPeopleRoute
  OperationsRiskRoute: typeof OperationsRiskRoute
  OperationsVendorsRoute: typeof OperationsVendorsRoute
  OperationsIndexRoute: typeof OperationsIndexRoute
  OperationsProgramsProgramIdRouteRoute: typeof OperationsProgramsProgramIdRouteRouteWithChildren
  OperationsProgramsEventsRoute: typeof OperationsProgramsEventsRoute
  OperationsProgramsIndexRoute: typeof OperationsProgramsIndexRoute
}

const OperationsRouteRouteChildren: OperationsRouteRouteChildren = {
  OperationsAdminRoute: OperationsAdminRoute,
  OperationsApplicationsRoute: OperationsApplicationsRoute,
  OperationsComplianceRoute: OperationsComplianceRoute,
  OperationsDocumentsRoute: OperationsDocumentsRoute,
  OperationsFinanceRoute: OperationsFinanceRoute,
  OperationsInsightsRoute: OperationsInsightsRoute,
  OperationsMarketingRoute: OperationsMarketingRoute,
  OperationsPeopleRoute: OperationsPeopleRoute,
  OperationsRiskRoute: OperationsRiskRoute,
  OperationsVendorsRoute: OperationsVendorsRoute,
  OperationsIndexRoute: OperationsIndexRoute,
  OperationsProgramsProgramIdRouteRoute:
    OperationsProgramsProgramIdRouteRouteWithChildren,
  OperationsProgramsEventsRoute: OperationsProgramsEventsRoute,
  OperationsProgramsIndexRoute: OperationsProgramsIndexRoute,
}

const OperationsRouteRouteWithChildren = OperationsRouteRoute._addFileChildren(
  OperationsRouteRouteChildren,
)

interface PublicRouteChildren {
  PublicAboutRoute: typeof PublicAboutRoute
  PublicContactRoute: typeof PublicContactRoute
  PublicDonateRoute: typeof PublicDonateRoute
  PublicPrivacyRoute: typeof PublicPrivacyRoute
  PublicTermsRoute: typeof PublicTermsRoute
  PublicIndexRoute: typeof PublicIndexRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicAboutRoute: PublicAboutRoute,
  PublicContactRoute: PublicContactRoute,
  PublicDonateRoute: PublicDonateRoute,
  PublicPrivacyRoute: PublicPrivacyRoute,
  PublicTermsRoute: PublicTermsRoute,
  PublicIndexRoute: PublicIndexRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

interface MyRouteChildren {
  MyIndexRoute: typeof MyIndexRoute
}

const MyRouteChildren: MyRouteChildren = {
  MyIndexRoute: MyIndexRoute,
}

const MyRouteWithChildren = MyRoute._addFileChildren(MyRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  OperationsRouteRoute: OperationsRouteRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
  MyRoute: MyRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
