/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as MyRouteImport } from './routes/my'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as OperationsRouteRouteImport } from './routes/operations/route'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as PublicAboutRouteImport } from './routes/_public/about'
import { Route as PublicContactRouteImport } from './routes/_public/contact'
import { Route as PublicDonateRouteImport } from './routes/_public/donate'
import { Route as PublicPrivacyRouteImport } from './routes/_public/privacy'
import { Route as PublicTermsRouteImport } from './routes/_public/terms'
import { Route as MyIndexRouteImport } from './routes/my/index'
import { Route as MyApplicationsRouteImport } from './routes/my/applications'
import { Route as MyApplyRouteImport } from './routes/my/apply'
import { Route as MyHealthRouteImport } from './routes/my/health'
import { Route as MyHouseholdRouteImport } from './routes/my/household'
import { Route as MyPaymentRouteImport } from './routes/my/payment'
import { Route as MyProgramsRouteImport } from './routes/my/programs'
import { Route as MyTravelRouteImport } from './routes/my/travel'
import { Route as MyWaiversRouteImport } from './routes/my/waivers'
import { Route as OperationsIndexRouteImport } from './routes/operations/index'
import { Route as OperationsAdminRouteImport } from './routes/operations/admin'
import { Route as OperationsApplicationsRouteImport } from './routes/operations/applications'
import { Route as OperationsComplianceRouteImport } from './routes/operations/compliance'
import { Route as OperationsDocumentsRouteImport } from './routes/operations/documents'
import { Route as OperationsFinanceRouteImport } from './routes/operations/finance'
import { Route as OperationsInsightsRouteImport } from './routes/operations/insights'
import { Route as OperationsMarketingRouteImport } from './routes/operations/marketing'
import { Route as OperationsPeopleRouteImport } from './routes/operations/people'
import { Route as OperationsRiskRouteImport } from './routes/operations/risk'
import { Route as OperationsVendorsRouteImport } from './routes/operations/vendors'
import { Route as PublicCampsIndexRouteImport } from './routes/_public/camps/index'
import { Route as PublicCampsSlugRouteImport } from './routes/_public/camps/$slug'
import { Route as MyApplicationsSubmissionIdRouteImport } from './routes/my/applications.$submissionId'
import { Route as MyHouseholdProfileIdRouteImport } from './routes/my/household.$profileId'
import { Route as MyProgramsInstanceIdRouteImport } from './routes/my/programs.$instanceId'
import { Route as OperationsApplicationsIndexRouteImport } from './routes/operations/applications/index'
import { Route as OperationsApplicationsSubmissionIdRouteImport } from './routes/operations/applications/$submissionId'
import { Route as OperationsApplicationsBuilderRouteImport } from './routes/operations/applications/builder'
import { Route as OperationsApplicationsInterviewsRouteImport } from './routes/operations/applications/interviews'
import { Route as OperationsApplicationsReviewRouteImport } from './routes/operations/applications/review'
import { Route as OperationsApplicationsSelectionRouteImport } from './routes/operations/applications/selection'
import { Route as OperationsProgramsIndexRouteImport } from './routes/operations/programs/index'
import { Route as OperationsProgramsProgramIdRouteRouteImport } from './routes/operations/programs/$programId/route'
import { Route as OperationsProgramsEventsRouteImport } from './routes/operations/programs/events'
import { Route as OperationsProgramsProgramIdIndexRouteImport } from './routes/operations/programs/$programId/index'
import { Route as OperationsProgramsProgramIdInstancesInstanceIdRouteImport } from './routes/operations/programs/$programId/instances/$instanceId'

const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const MyRoute = MyRouteImport.update({
  id: '/my',
  path: '/my',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const OperationsRouteRoute = OperationsRouteRouteImport.update({
  id: '/operations',
  path: '/operations',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicAboutRoute = PublicAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => PublicRoute,
} as any)
const PublicContactRoute = PublicContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => PublicRoute,
} as any)
const PublicDonateRoute = PublicDonateRouteImport.update({
  id: '/donate',
  path: '/donate',
  getParentRoute: () => PublicRoute,
} as any)
const PublicPrivacyRoute = PublicPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => PublicRoute,
} as any)
const PublicTermsRoute = PublicTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => PublicRoute,
} as any)
const MyIndexRoute = MyIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MyRoute,
} as any)
const MyApplicationsRoute = MyApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => MyRoute,
} as any)
const MyApplyRoute = MyApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => MyRoute,
} as any)
const MyHealthRoute = MyHealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => MyRoute,
} as any)
const MyHouseholdRoute = MyHouseholdRouteImport.update({
  id: '/household',
  path: '/household',
  getParentRoute: () => MyRoute,
} as any)
const MyPaymentRoute = MyPaymentRouteImport.update({
  id: '/payment',
  path: '/payment',
  getParentRoute: () => MyRoute,
} as any)
const MyProgramsRoute = MyProgramsRouteImport.update({
  id: '/programs',
  path: '/programs',
  getParentRoute: () => MyRoute,
} as any)
const MyTravelRoute = MyTravelRouteImport.update({
  id: '/travel',
  path: '/travel',
  getParentRoute: () => MyRoute,
} as any)
const MyWaiversRoute = MyWaiversRouteImport.update({
  id: '/waivers',
  path: '/waivers',
  getParentRoute: () => MyRoute,
} as any)
const OperationsIndexRoute = OperationsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OperationsRouteRoute,
} as any)
const OperationsAdminRoute = OperationsAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => OperationsRouteRoute,
} as any)
const OperationsApplicationsRoute = OperationsApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => OperationsRouteRoute,
} as any)
const OperationsComplianceRoute = OperationsComplianceRouteImport.update({
  id: '/compliance',
  path: '/compliance',
  getParentRoute: () => OperationsRouteRoute,
} as any)
const OperationsDocumentsRoute = OperationsDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => OperationsRouteRoute,
} as any)
const OperationsFinanceRoute = OperationsFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => OperationsRouteRoute,
} as any)
const OperationsInsightsRoute = OperationsInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => OperationsRouteRoute,
} as any)
const OperationsMarketingRoute = OperationsMarketingRouteImport.update({
  id: '/marketing',
  path: '/marketing',
  getParentRoute: () => OperationsRouteRoute,
} as any)
const OperationsPeopleRoute = OperationsPeopleRouteImport.update({
  id: '/people',
  path: '/people',
  getParentRoute: () => OperationsRouteRoute,
} as any)
const OperationsRiskRoute = OperationsRiskRouteImport.update({
  id: '/risk',
  path: '/risk',
  getParentRoute: () => OperationsRouteRoute,
} as any)
const OperationsVendorsRoute = OperationsVendorsRouteImport.update({
  id: '/vendors',
  path: '/vendors',
  getParentRoute: () => OperationsRouteRoute,
} as any)
const PublicCampsIndexRoute = PublicCampsIndexRouteImport.update({
  id: '/camps/',
  path: '/camps/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicCampsSlugRoute = PublicCampsSlugRouteImport.update({
  id: '/camps/$slug',
  path: '/camps/$slug',
  getParentRoute: () => PublicRoute,
} as any)
const MyApplicationsSubmissionIdRoute =
  MyApplicationsSubmissionIdRouteImport.update({
    id: '/$submissionId',
    path: '/$submissionId',
    getParentRoute: () => MyApplicationsRoute,
  } as any)
const MyHouseholdProfileIdRoute = MyHouseholdProfileIdRouteImport.update({
  id: '/$profileId',
  path: '/$profileId',
  getParentRoute: () => MyHouseholdRoute,
} as any)
const MyProgramsInstanceIdRoute = MyProgramsInstanceIdRouteImport.update({
  id: '/$instanceId',
  path: '/$instanceId',
  getParentRoute: () => MyProgramsRoute,
} as any)
const OperationsApplicationsIndexRoute =
  OperationsApplicationsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => OperationsApplicationsRoute,
  } as any)
const OperationsApplicationsSubmissionIdRoute =
  OperationsApplicationsSubmissionIdRouteImport.update({
    id: '/$submissionId',
    path: '/$submissionId',
    getParentRoute: () => OperationsApplicationsRoute,
  } as any)
const OperationsApplicationsBuilderRoute =
  OperationsApplicationsBuilderRouteImport.update({
    id: '/builder',
    path: '/builder',
    getParentRoute: () => OperationsApplicationsRoute,
  } as any)
const OperationsApplicationsInterviewsRoute =
  OperationsApplicationsInterviewsRouteImport.update({
    id: '/interviews',
    path: '/interviews',
    getParentRoute: () => OperationsApplicationsRoute,
  } as any)
const OperationsApplicationsReviewRoute =
  OperationsApplicationsReviewRouteImport.update({
    id: '/review',
    path: '/review',
    getParentRoute: () => OperationsApplicationsRoute,
  } as any)
const OperationsApplicationsSelectionRoute =
  OperationsApplicationsSelectionRouteImport.update({
    id: '/selection',
    path: '/selection',
    getParentRoute: () => OperationsApplicationsRoute,
  } as any)
const OperationsProgramsIndexRoute = OperationsProgramsIndexRouteImport.update({
  id: '/programs/',
  path: '/programs/',
  getParentRoute: () => OperationsRouteRoute,
} as any)
const OperationsProgramsProgramIdRouteRoute =
  OperationsProgramsProgramIdRouteRouteImport.update({
    id: '/programs/$programId',
    path: '/programs/$programId',
    getParentRoute: () => OperationsRouteRoute,
  } as any)
const OperationsProgramsEventsRoute =
  OperationsProgramsEventsRouteImport.update({
    id: '/programs/events',
    path: '/programs/events',
    getParentRoute: () => OperationsRouteRoute,
  } as any)
const OperationsProgramsProgramIdIndexRoute =
  OperationsProgramsProgramIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => OperationsProgramsProgramIdRouteRoute,
  } as any)
const OperationsProgramsProgramIdInstancesInstanceIdRoute =
  OperationsProgramsProgramIdInstancesInstanceIdRouteImport.update({
    id: '/instances/$instanceId',
    path: '/instances/$instanceId',
    getParentRoute: () => OperationsProgramsProgramIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/operations': typeof OperationsRouteRouteWithChildren
  '/': typeof PublicIndexRoute
  '/my': typeof MyRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/verify-email': typeof VerifyEmailRoute
  '/about': typeof PublicAboutRoute
  '/contact': typeof PublicContactRoute
  '/donate': typeof PublicDonateRoute
  '/privacy': typeof PublicPrivacyRoute
  '/terms': typeof PublicTermsRoute
  '/my/applications': typeof MyApplicationsRouteWithChildren
  '/my/apply': typeof MyApplyRoute
  '/my/health': typeof MyHealthRoute
  '/my/household': typeof MyHouseholdRouteWithChildren
  '/my/payment': typeof MyPaymentRoute
  '/my/programs': typeof MyProgramsRouteWithChildren
  '/my/travel': typeof MyTravelRoute
  '/my/waivers': typeof MyWaiversRoute
  '/operations/admin': typeof OperationsAdminRoute
  '/operations/applications': typeof OperationsApplicationsRouteWithChildren
  '/operations/compliance': typeof OperationsComplianceRoute
  '/operations/documents': typeof OperationsDocumentsRoute
  '/operations/finance': typeof OperationsFinanceRoute
  '/operations/insights': typeof OperationsInsightsRoute
  '/operations/marketing': typeof OperationsMarketingRoute
  '/operations/people': typeof OperationsPeopleRoute
  '/operations/risk': typeof OperationsRiskRoute
  '/operations/vendors': typeof OperationsVendorsRoute
  '/my/': typeof MyIndexRoute
  '/operations/': typeof OperationsIndexRoute
  '/operations/programs/$programId': typeof OperationsProgramsProgramIdRouteRouteWithChildren
  '/camps/$slug': typeof PublicCampsSlugRoute
  '/my/applications/$submissionId': typeof MyApplicationsSubmissionIdRoute
  '/my/household/$profileId': typeof MyHouseholdProfileIdRoute
  '/my/programs/$instanceId': typeof MyProgramsInstanceIdRoute
  '/operations/applications/$submissionId': typeof OperationsApplicationsSubmissionIdRoute
  '/operations/applications/builder': typeof OperationsApplicationsBuilderRoute
  '/operations/applications/interviews': typeof OperationsApplicationsInterviewsRoute
  '/operations/applications/review': typeof OperationsApplicationsReviewRoute
  '/operations/applications/selection': typeof OperationsApplicationsSelectionRoute
  '/operations/programs/events': typeof OperationsProgramsEventsRoute
  '/camps/': typeof PublicCampsIndexRoute
  '/operations/applications/': typeof OperationsApplicationsIndexRoute
  '/operations/programs/': typeof OperationsProgramsIndexRoute
  '/operations/programs/$programId/': typeof OperationsProgramsProgramIdIndexRoute
  '/operations/programs/$programId/instances/$instanceId': typeof OperationsProgramsProgramIdInstancesInstanceIdRoute
}
export interface FileRoutesByTo {
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/verify-email': typeof VerifyEmailRoute
  '/about': typeof PublicAboutRoute
  '/contact': typeof PublicContactRoute
  '/donate': typeof PublicDonateRoute
  '/privacy': typeof PublicPrivacyRoute
  '/terms': typeof PublicTermsRoute
  '/my/applications': typeof MyApplicationsRouteWithChildren
  '/my/apply': typeof MyApplyRoute
  '/my/health': typeof MyHealthRoute
  '/my/household': typeof MyHouseholdRouteWithChildren
  '/my/payment': typeof MyPaymentRoute
  '/my/programs': typeof MyProgramsRouteWithChildren
  '/my/travel': typeof MyTravelRoute
  '/my/waivers': typeof MyWaiversRoute
  '/operations/admin': typeof OperationsAdminRoute
  '/operations/compliance': typeof OperationsComplianceRoute
  '/operations/documents': typeof OperationsDocumentsRoute
  '/operations/finance': typeof OperationsFinanceRoute
  '/operations/insights': typeof OperationsInsightsRoute
  '/operations/marketing': typeof OperationsMarketingRoute
  '/operations/people': typeof OperationsPeopleRoute
  '/operations/risk': typeof OperationsRiskRoute
  '/operations/vendors': typeof OperationsVendorsRoute
  '/': typeof PublicIndexRoute
  '/my': typeof MyIndexRoute
  '/operations': typeof OperationsIndexRoute
  '/camps/$slug': typeof PublicCampsSlugRoute
  '/my/applications/$submissionId': typeof MyApplicationsSubmissionIdRoute
  '/my/household/$profileId': typeof MyHouseholdProfileIdRoute
  '/my/programs/$instanceId': typeof MyProgramsInstanceIdRoute
  '/operations/applications/$submissionId': typeof OperationsApplicationsSubmissionIdRoute
  '/operations/applications/builder': typeof OperationsApplicationsBuilderRoute
  '/operations/applications/interviews': typeof OperationsApplicationsInterviewsRoute
  '/operations/applications/review': typeof OperationsApplicationsReviewRoute
  '/operations/applications/selection': typeof OperationsApplicationsSelectionRoute
  '/operations/programs/events': typeof OperationsProgramsEventsRoute
  '/camps': typeof PublicCampsIndexRoute
  '/operations/applications': typeof OperationsApplicationsIndexRoute
  '/operations/programs': typeof OperationsProgramsIndexRoute
  '/operations/programs/$programId': typeof OperationsProgramsProgramIdIndexRoute
  '/operations/programs/$programId/instances/$instanceId': typeof OperationsProgramsProgramIdInstancesInstanceIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/operations': typeof OperationsRouteRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/my': typeof MyRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/verify-email': typeof VerifyEmailRoute
  '/_public/about': typeof PublicAboutRoute
  '/_public/contact': typeof PublicContactRoute
  '/_public/donate': typeof PublicDonateRoute
  '/_public/privacy': typeof PublicPrivacyRoute
  '/_public/terms': typeof PublicTermsRoute
  '/my/applications': typeof MyApplicationsRouteWithChildren
  '/my/apply': typeof MyApplyRoute
  '/my/health': typeof MyHealthRoute
  '/my/household': typeof MyHouseholdRouteWithChildren
  '/my/payment': typeof MyPaymentRoute
  '/my/programs': typeof MyProgramsRouteWithChildren
  '/my/travel': typeof MyTravelRoute
  '/my/waivers': typeof MyWaiversRoute
  '/operations/admin': typeof OperationsAdminRoute
  '/operations/applications': typeof OperationsApplicationsRouteWithChildren
  '/operations/compliance': typeof OperationsComplianceRoute
  '/operations/documents': typeof OperationsDocumentsRoute
  '/operations/finance': typeof OperationsFinanceRoute
  '/operations/insights': typeof OperationsInsightsRoute
  '/operations/marketing': typeof OperationsMarketingRoute
  '/operations/people': typeof OperationsPeopleRoute
  '/operations/risk': typeof OperationsRiskRoute
  '/operations/vendors': typeof OperationsVendorsRoute
  '/_public/': typeof PublicIndexRoute
  '/my/': typeof MyIndexRoute
  '/operations/': typeof OperationsIndexRoute
  '/operations/programs/$programId': typeof OperationsProgramsProgramIdRouteRouteWithChildren
  '/_public/camps/$slug': typeof PublicCampsSlugRoute
  '/my/applications/$submissionId': typeof MyApplicationsSubmissionIdRoute
  '/my/household/$profileId': typeof MyHouseholdProfileIdRoute
  '/my/programs/$instanceId': typeof MyProgramsInstanceIdRoute
  '/operations/applications/$submissionId': typeof OperationsApplicationsSubmissionIdRoute
  '/operations/applications/builder': typeof OperationsApplicationsBuilderRoute
  '/operations/applications/interviews': typeof OperationsApplicationsInterviewsRoute
  '/operations/applications/review': typeof OperationsApplicationsReviewRoute
  '/operations/applications/selection': typeof OperationsApplicationsSelectionRoute
  '/operations/programs/events': typeof OperationsProgramsEventsRoute
  '/_public/camps/': typeof PublicCampsIndexRoute
  '/operations/applications/': typeof OperationsApplicationsIndexRoute
  '/operations/programs/': typeof OperationsProgramsIndexRoute
  '/operations/programs/$programId/': typeof OperationsProgramsProgramIdIndexRoute
  '/operations/programs/$programId/instances/$instanceId': typeof OperationsProgramsProgramIdInstancesInstanceIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/operations'
    | '/'
    | '/my'
    | '/onboarding'
    | '/signup'
    | '/verify-email'
    | '/about'
    | '/contact'
    | '/donate'
    | '/privacy'
    | '/terms'
    | '/my/applications'
    | '/my/apply'
    | '/my/health'
    | '/my/household'
    | '/my/payment'
    | '/my/programs'
    | '/my/travel'
    | '/my/waivers'
    | '/operations/admin'
    | '/operations/applications'
    | '/operations/compliance'
    | '/operations/documents'
    | '/operations/finance'
    | '/operations/insights'
    | '/operations/marketing'
    | '/operations/people'
    | '/operations/risk'
    | '/operations/vendors'
    | '/my/'
    | '/operations/'
    | '/operations/programs/$programId'
    | '/camps/$slug'
    | '/my/applications/$submissionId'
    | '/my/household/$profileId'
    | '/my/programs/$instanceId'
    | '/operations/applications/$submissionId'
    | '/operations/applications/builder'
    | '/operations/applications/interviews'
    | '/operations/applications/review'
    | '/operations/applications/selection'
    | '/operations/programs/events'
    | '/camps/'
    | '/operations/applications/'
    | '/operations/programs/'
    | '/operations/programs/$programId/'
    | '/operations/programs/$programId/instances/$instanceId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/onboarding'
    | '/signup'
    | '/verify-email'
    | '/about'
    | '/contact'
    | '/donate'
    | '/privacy'
    | '/terms'
    | '/my/applications'
    | '/my/apply'
    | '/my/health'
    | '/my/household'
    | '/my/payment'
    | '/my/programs'
    | '/my/travel'
    | '/my/waivers'
    | '/operations/admin'
    | '/operations/compliance'
    | '/operations/documents'
    | '/operations/finance'
    | '/operations/insights'
    | '/operations/marketing'
    | '/operations/people'
    | '/operations/risk'
    | '/operations/vendors'
    | '/'
    | '/my'
    | '/operations'
    | '/camps/$slug'
    | '/my/applications/$submissionId'
    | '/my/household/$profileId'
    | '/my/programs/$instanceId'
    | '/operations/applications/$submissionId'
    | '/operations/applications/builder'
    | '/operations/applications/interviews'
    | '/operations/applications/review'
    | '/operations/applications/selection'
    | '/operations/programs/events'
    | '/camps'
    | '/operations/applications'
    | '/operations/programs'
    | '/operations/programs/$programId'
    | '/operations/programs/$programId/instances/$instanceId'
  id:
    | '__root__'
    | '/operations'
    | '/_public'
    | '/my'
    | '/onboarding'
    | '/signup'
    | '/verify-email'
    | '/_public/about'
    | '/_public/contact'
    | '/_public/donate'
    | '/_public/privacy'
    | '/_public/terms'
    | '/my/applications'
    | '/my/apply'
    | '/my/health'
    | '/my/household'
    | '/my/payment'
    | '/my/programs'
    | '/my/travel'
    | '/my/waivers'
    | '/operations/admin'
    | '/operations/applications'
    | '/operations/compliance'
    | '/operations/documents'
    | '/operations/finance'
    | '/operations/insights'
    | '/operations/marketing'
    | '/operations/people'
    | '/operations/risk'
    | '/operations/vendors'
    | '/_public/'
    | '/my/'
    | '/operations/'
    | '/operations/programs/$programId'
    | '/_public/camps/$slug'
    | '/my/applications/$submissionId'
    | '/my/household/$profileId'
    | '/my/programs/$instanceId'
    | '/operations/applications/$submissionId'
    | '/operations/applications/builder'
    | '/operations/applications/interviews'
    | '/operations/applications/review'
    | '/operations/applications/selection'
    | '/operations/programs/events'
    | '/_public/camps/'
    | '/operations/applications/'
    | '/operations/programs/'
    | '/operations/programs/$programId/'
    | '/operations/programs/$programId/instances/$instanceId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  OperationsRouteRoute: typeof OperationsRouteRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
  MyRoute: typeof MyRouteWithChildren
  OnboardingRoute: typeof OnboardingRoute
  SignupRoute: typeof SignupRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my': {
      id: '/my'
      path: '/my'
      fullPath: '/my'
      preLoaderRoute: typeof MyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operations': {
      id: '/operations'
      path: '/operations'
      fullPath: '/operations'
      preLoaderRoute: typeof OperationsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/about': {
      id: '/_public/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof PublicAboutRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/contact': {
      id: '/_public/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof PublicContactRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/donate': {
      id: '/_public/donate'
      path: '/donate'
      fullPath: '/donate'
      preLoaderRoute: typeof PublicDonateRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/privacy': {
      id: '/_public/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PublicPrivacyRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/terms': {
      id: '/_public/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof PublicTermsRouteImport
      parentRoute: typeof PublicRoute
    }
    '/my/': {
      id: '/my/'
      path: '/'
      fullPath: '/my/'
      preLoaderRoute: typeof MyIndexRouteImport
      parentRoute: typeof MyRoute
    }
    '/my/applications': {
      id: '/my/applications'
      path: '/applications'
      fullPath: '/my/applications'
      preLoaderRoute: typeof MyApplicationsRouteImport
      parentRoute: typeof MyRoute
    }
    '/my/apply': {
      id: '/my/apply'
      path: '/apply'
      fullPath: '/my/apply'
      preLoaderRoute: typeof MyApplyRouteImport
      parentRoute: typeof MyRoute
    }
    '/my/health': {
      id: '/my/health'
      path: '/health'
      fullPath: '/my/health'
      preLoaderRoute: typeof MyHealthRouteImport
      parentRoute: typeof MyRoute
    }
    '/my/household': {
      id: '/my/household'
      path: '/household'
      fullPath: '/my/household'
      preLoaderRoute: typeof MyHouseholdRouteImport
      parentRoute: typeof MyRoute
    }
    '/my/payment': {
      id: '/my/payment'
      path: '/payment'
      fullPath: '/my/payment'
      preLoaderRoute: typeof MyPaymentRouteImport
      parentRoute: typeof MyRoute
    }
    '/my/programs': {
      id: '/my/programs'
      path: '/programs'
      fullPath: '/my/programs'
      preLoaderRoute: typeof MyProgramsRouteImport
      parentRoute: typeof MyRoute
    }
    '/my/travel': {
      id: '/my/travel'
      path: '/travel'
      fullPath: '/my/travel'
      preLoaderRoute: typeof MyTravelRouteImport
      parentRoute: typeof MyRoute
    }
    '/my/waivers': {
      id: '/my/waivers'
      path: '/waivers'
      fullPath: '/my/waivers'
      preLoaderRoute: typeof MyWaiversRouteImport
      parentRoute: typeof MyRoute
    }
    '/operations/': {
      id: '/operations/'
      path: '/'
      fullPath: '/operations/'
      preLoaderRoute: typeof OperationsIndexRouteImport
      parentRoute: typeof OperationsRouteRoute
    }
    '/operations/admin': {
      id: '/operations/admin'
      path: '/admin'
      fullPath: '/operations/admin'
      preLoaderRoute: typeof OperationsAdminRouteImport
      parentRoute: typeof OperationsRouteRoute
    }
    '/operations/applications': {
      id: '/operations/applications'
      path: '/applications'
      fullPath: '/operations/applications'
      preLoaderRoute: typeof OperationsApplicationsRouteImport
      parentRoute: typeof OperationsRouteRoute
    }
    '/operations/compliance': {
      id: '/operations/compliance'
      path: '/compliance'
      fullPath: '/operations/compliance'
      preLoaderRoute: typeof OperationsComplianceRouteImport
      parentRoute: typeof OperationsRouteRoute
    }
    '/operations/documents': {
      id: '/operations/documents'
      path: '/documents'
      fullPath: '/operations/documents'
      preLoaderRoute: typeof OperationsDocumentsRouteImport
      parentRoute: typeof OperationsRouteRoute
    }
    '/operations/finance': {
      id: '/operations/finance'
      path: '/finance'
      fullPath: '/operations/finance'
      preLoaderRoute: typeof OperationsFinanceRouteImport
      parentRoute: typeof OperationsRouteRoute
    }
    '/operations/insights': {
      id: '/operations/insights'
      path: '/insights'
      fullPath: '/operations/insights'
      preLoaderRoute: typeof OperationsInsightsRouteImport
      parentRoute: typeof OperationsRouteRoute
    }
    '/operations/marketing': {
      id: '/operations/marketing'
      path: '/marketing'
      fullPath: '/operations/marketing'
      preLoaderRoute: typeof OperationsMarketingRouteImport
      parentRoute: typeof OperationsRouteRoute
    }
    '/operations/people': {
      id: '/operations/people'
      path: '/people'
      fullPath: '/operations/people'
      preLoaderRoute: typeof OperationsPeopleRouteImport
      parentRoute: typeof OperationsRouteRoute
    }
    '/operations/risk': {
      id: '/operations/risk'
      path: '/risk'
      fullPath: '/operations/risk'
      preLoaderRoute: typeof OperationsRiskRouteImport
      parentRoute: typeof OperationsRouteRoute
    }
    '/operations/vendors': {
      id: '/operations/vendors'
      path: '/vendors'
      fullPath: '/operations/vendors'
      preLoaderRoute: typeof OperationsVendorsRouteImport
      parentRoute: typeof OperationsRouteRoute
    }
    '/_public/camps/': {
      id: '/_public/camps/'
      path: '/camps'
      fullPath: '/camps/'
      preLoaderRoute: typeof PublicCampsIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/camps/$slug': {
      id: '/_public/camps/$slug'
      path: '/camps/$slug'
      fullPath: '/camps/$slug'
      preLoaderRoute: typeof PublicCampsSlugRouteImport
      parentRoute: typeof PublicRoute
    }
    '/my/applications/$submissionId': {
      id: '/my/applications/$submissionId'
      path: '/$submissionId'
      fullPath: '/my/applications/$submissionId'
      preLoaderRoute: typeof MyApplicationsSubmissionIdRouteImport
      parentRoute: typeof MyApplicationsRoute
    }
    '/my/household/$profileId': {
      id: '/my/household/$profileId'
      path: '/$profileId'
      fullPath: '/my/household/$profileId'
      preLoaderRoute: typeof MyHouseholdProfileIdRouteImport
      parentRoute: typeof MyHouseholdRoute
    }
    '/my/programs/$instanceId': {
      id: '/my/programs/$instanceId'
      path: '/$instanceId'
      fullPath: '/my/programs/$instanceId'
      preLoaderRoute: typeof MyProgramsInstanceIdRouteImport
      parentRoute: typeof MyProgramsRoute
    }
    '/operations/applications/': {
      id: '/operations/applications/'
      path: '/'
      fullPath: '/operations/applications/'
      preLoaderRoute: typeof OperationsApplicationsIndexRouteImport
      parentRoute: typeof OperationsApplicationsRoute
    }
    '/operations/applications/$submissionId': {
      id: '/operations/applications/$submissionId'
      path: '/$submissionId'
      fullPath: '/operations/applications/$submissionId'
      preLoaderRoute: typeof OperationsApplicationsSubmissionIdRouteImport
      parentRoute: typeof OperationsApplicationsRoute
    }
    '/operations/applications/builder': {
      id: '/operations/applications/builder'
      path: '/builder'
      fullPath: '/operations/applications/builder'
      preLoaderRoute: typeof OperationsApplicationsBuilderRouteImport
      parentRoute: typeof OperationsApplicationsRoute
    }
    '/operations/applications/interviews': {
      id: '/operations/applications/interviews'
      path: '/interviews'
      fullPath: '/operations/applications/interviews'
      preLoaderRoute: typeof OperationsApplicationsInterviewsRouteImport
      parentRoute: typeof OperationsApplicationsRoute
    }
    '/operations/applications/review': {
      id: '/operations/applications/review'
      path: '/review'
      fullPath: '/operations/applications/review'
      preLoaderRoute: typeof OperationsApplicationsReviewRouteImport
      parentRoute: typeof OperationsApplicationsRoute
    }
    '/operations/applications/selection': {
      id: '/operations/applications/selection'
      path: '/selection'
      fullPath: '/operations/applications/selection'
      preLoaderRoute: typeof OperationsApplicationsSelectionRouteImport
      parentRoute: typeof OperationsApplicationsRoute
    }
    '/operations/programs/': {
      id: '/operations/programs/'
      path: '/programs'
      fullPath: '/operations/programs/'
      preLoaderRoute: typeof OperationsProgramsIndexRouteImport
      parentRoute: typeof OperationsRouteRoute
    }
    '/operations/programs/$programId': {
      id: '/operations/programs/$programId'
      path: '/programs/$programId'
      fullPath: '/operations/programs/$programId'
      preLoaderRoute: typeof OperationsProgramsProgramIdRouteRouteImport
      parentRoute: typeof OperationsRouteRoute
    }
    '/operations/programs/events': {
      id: '/operations/programs/events'
      path: '/programs/events'
      fullPath: '/operations/programs/events'
      preLoaderRoute: typeof OperationsProgramsEventsRouteImport
      parentRoute: typeof OperationsRouteRoute
    }
    '/operations/programs/$programId/': {
      id: '/operations/programs/$programId/'
      path: '/'
      fullPath: '/operations/programs/$programId/'
      preLoaderRoute: typeof OperationsProgramsProgramIdIndexRouteImport
      parentRoute: typeof OperationsProgramsProgramIdRouteRoute
    }
    '/operations/programs/$programId/instances/$instanceId': {
      id: '/operations/programs/$programId/instances/$instanceId'
      path: '/instances/$instanceId'
      fullPath: '/operations/programs/$programId/instances/$instanceId'
      preLoaderRoute: typeof OperationsProgramsProgramIdInstancesInstanceIdRouteImport
      parentRoute: typeof OperationsProgramsProgramIdRouteRoute
    }
  }
}

interface OperationsApplicationsRouteChildren {
  OperationsApplicationsSubmissionIdRoute: typeof OperationsApplicationsSubmissionIdRoute
  OperationsApplicationsBuilderRoute: typeof OperationsApplicationsBuilderRoute
  OperationsApplicationsInterviewsRoute: typeof OperationsApplicationsInterviewsRoute
  OperationsApplicationsReviewRoute: typeof OperationsApplicationsReviewRoute
  OperationsApplicationsSelectionRoute: typeof OperationsApplicationsSelectionRoute
  OperationsApplicationsIndexRoute: typeof OperationsApplicationsIndexRoute
}

const OperationsApplicationsRouteChildren: OperationsApplicationsRouteChildren =
  {
    OperationsApplicationsSubmissionIdRoute:
      OperationsApplicationsSubmissionIdRoute,
    OperationsApplicationsBuilderRoute: OperationsApplicationsBuilderRoute,
    OperationsApplicationsInterviewsRoute:
      OperationsApplicationsInterviewsRoute,
    OperationsApplicationsReviewRoute: OperationsApplicationsReviewRoute,
    OperationsApplicationsSelectionRoute: OperationsApplicationsSelectionRoute,
    OperationsApplicationsIndexRoute: OperationsApplicationsIndexRoute,
  }

const OperationsApplicationsRouteWithChildren =
  OperationsApplicationsRoute._addFileChildren(
    OperationsApplicationsRouteChildren,
  )

interface OperationsProgramsProgramIdRouteRouteChildren {
  OperationsProgramsProgramIdIndexRoute: typeof OperationsProgramsProgramIdIndexRoute
  OperationsProgramsProgramIdInstancesInstanceIdRoute: typeof OperationsProgramsProgramIdInstancesInstanceIdRoute
}

const OperationsProgramsProgramIdRouteRouteChildren: OperationsProgramsProgramIdRouteRouteChildren =
  {
    OperationsProgramsProgramIdIndexRoute:
      OperationsProgramsProgramIdIndexRoute,
    OperationsProgramsProgramIdInstancesInstanceIdRoute:
      OperationsProgramsProgramIdInstancesInstanceIdRoute,
  }

const OperationsProgramsProgramIdRouteRouteWithChildren =
  OperationsProgramsProgramIdRouteRoute._addFileChildren(
    OperationsProgramsProgramIdRouteRouteChildren,
  )

interface OperationsRouteRouteChildren {
  OperationsAdminRoute: typeof OperationsAdminRoute
  OperationsApplicationsRoute: typeof OperationsApplicationsRouteWithChildren
  OperationsComplianceRoute: typeof OperationsComplianceRoute
  OperationsDocumentsRoute: typeof OperationsDocumentsRoute
  OperationsFinanceRoute: typeof OperationsFinanceRoute
  OperationsInsightsRoute: typeof OperationsInsightsRoute
  OperationsMarketingRoute: typeof OperationsMarketingRoute
  OperationsPeopleRoute: typeof OperationsPeopleRoute
  OperationsRiskRoute: typeof OperationsRiskRoute
  OperationsVendorsRoute: typeof OperationsVendorsRoute
  OperationsIndexRoute: typeof OperationsIndexRoute
  OperationsProgramsProgramIdRouteRoute: typeof OperationsProgramsProgramIdRouteRouteWithChildren
  OperationsProgramsEventsRoute: typeof OperationsProgramsEventsRoute
  OperationsProgramsIndexRoute: typeof OperationsProgramsIndexRoute
}

const OperationsRouteRouteChildren: OperationsRouteRouteChildren = {
  OperationsAdminRoute: OperationsAdminRoute,
  OperationsApplicationsRoute: OperationsApplicationsRouteWithChildren,
  OperationsComplianceRoute: OperationsComplianceRoute,
  OperationsDocumentsRoute: OperationsDocumentsRoute,
  OperationsFinanceRoute: OperationsFinanceRoute,
  OperationsInsightsRoute: OperationsInsightsRoute,
  OperationsMarketingRoute: OperationsMarketingRoute,
  OperationsPeopleRoute: OperationsPeopleRoute,
  OperationsRiskRoute: OperationsRiskRoute,
  OperationsVendorsRoute: OperationsVendorsRoute,
  OperationsIndexRoute: OperationsIndexRoute,
  OperationsProgramsProgramIdRouteRoute:
    OperationsProgramsProgramIdRouteRouteWithChildren,
  OperationsProgramsEventsRoute: OperationsProgramsEventsRoute,
  OperationsProgramsIndexRoute: OperationsProgramsIndexRoute,
}

const OperationsRouteRouteWithChildren = OperationsRouteRoute._addFileChildren(
  OperationsRouteRouteChildren,
)

interface PublicRouteChildren {
  PublicAboutRoute: typeof PublicAboutRoute
  PublicContactRoute: typeof PublicContactRoute
  PublicDonateRoute: typeof PublicDonateRoute
  PublicPrivacyRoute: typeof PublicPrivacyRoute
  PublicTermsRoute: typeof PublicTermsRoute
  PublicIndexRoute: typeof PublicIndexRoute
  PublicCampsSlugRoute: typeof PublicCampsSlugRoute
  PublicCampsIndexRoute: typeof PublicCampsIndexRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicAboutRoute: PublicAboutRoute,
  PublicContactRoute: PublicContactRoute,
  PublicDonateRoute: PublicDonateRoute,
  PublicPrivacyRoute: PublicPrivacyRoute,
  PublicTermsRoute: PublicTermsRoute,
  PublicIndexRoute: PublicIndexRoute,
  PublicCampsSlugRoute: PublicCampsSlugRoute,
  PublicCampsIndexRoute: PublicCampsIndexRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

interface MyApplicationsRouteChildren {
  MyApplicationsSubmissionIdRoute: typeof MyApplicationsSubmissionIdRoute
}

const MyApplicationsRouteChildren: MyApplicationsRouteChildren = {
  MyApplicationsSubmissionIdRoute: MyApplicationsSubmissionIdRoute,
}

const MyApplicationsRouteWithChildren = MyApplicationsRoute._addFileChildren(
  MyApplicationsRouteChildren,
)

interface MyHouseholdRouteChildren {
  MyHouseholdProfileIdRoute: typeof MyHouseholdProfileIdRoute
}

const MyHouseholdRouteChildren: MyHouseholdRouteChildren = {
  MyHouseholdProfileIdRoute: MyHouseholdProfileIdRoute,
}

const MyHouseholdRouteWithChildren = MyHouseholdRoute._addFileChildren(
  MyHouseholdRouteChildren,
)

interface MyProgramsRouteChildren {
  MyProgramsInstanceIdRoute: typeof MyProgramsInstanceIdRoute
}

const MyProgramsRouteChildren: MyProgramsRouteChildren = {
  MyProgramsInstanceIdRoute: MyProgramsInstanceIdRoute,
}

const MyProgramsRouteWithChildren = MyProgramsRoute._addFileChildren(
  MyProgramsRouteChildren,
)

interface MyRouteChildren {
  MyApplicationsRoute: typeof MyApplicationsRouteWithChildren
  MyApplyRoute: typeof MyApplyRoute
  MyHealthRoute: typeof MyHealthRoute
  MyHouseholdRoute: typeof MyHouseholdRouteWithChildren
  MyPaymentRoute: typeof MyPaymentRoute
  MyProgramsRoute: typeof MyProgramsRouteWithChildren
  MyTravelRoute: typeof MyTravelRoute
  MyWaiversRoute: typeof MyWaiversRoute
  MyIndexRoute: typeof MyIndexRoute
}

const MyRouteChildren: MyRouteChildren = {
  MyApplicationsRoute: MyApplicationsRouteWithChildren,
  MyApplyRoute: MyApplyRoute,
  MyHealthRoute: MyHealthRoute,
  MyHouseholdRoute: MyHouseholdRouteWithChildren,
  MyPaymentRoute: MyPaymentRoute,
  MyProgramsRoute: MyProgramsRouteWithChildren,
  MyTravelRoute: MyTravelRoute,
  MyWaiversRoute: MyWaiversRoute,
  MyIndexRoute: MyIndexRoute,
}

const MyRouteWithChildren = MyRoute._addFileChildren(MyRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  OperationsRouteRoute: OperationsRouteRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
  MyRoute: MyRouteWithChildren,
  OnboardingRoute: OnboardingRoute,
  SignupRoute: SignupRoute,
  VerifyEmailRoute: VerifyEmailRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
